@startuml

actor Taker
box Valorem #LightGreen
participant Quay
end box
actor "Market Maker" as MM
box Valorem #LightBlue
participant SettlementEngine as SE
end box

== Initialisation ==
MM -> Quay: Authenticate
MM -> Quay: gRPC: MM RFQ Stream
Quay -> MM: gRPC: MM RFQ Stream

== Case: Market Maker Offer, Taker doesn't execute ==
Taker --> SE: newOptionType(...)
SE --> Taker: optionId
Taker -> Quay: gRPC: RFQ\nQuoteRequest{ulid=None}
Quay -> Taker: gRPC: Taker RFQ Stream
Quay -> MM: gRPC: MM RFQ Stream\nQuoteRequest{ulid=Some}
MM -> SE: option(...)
SE -> MM: optionInfo
MM -> SE: write(...)
SE -> MM: claimId
MM -> Quay: gRPC: MM RFQ Stream\nQuoteResponse{\n\tulid=Some,\n\tOffer=Some\n}
Quay -> Taker: gRPC: Taker RFQ Stream\nQuoteResponse{Offer=Some}
Quay -[#red]X Taker: gRPC: Taker RFQ Stream\nClose
hnote over Taker #lightBlue
[Start of exercise window]
end hnote
hnote over Taker #lightBlue
[ End of exercise window ]
end hnote
MM -> SE: redeem(...)
@enduml