@startuml

actor Trader
box Valorem #LightGreen
participant Quay
end box
actor "Market Maker" as MM

== Case: Market Maker Prices ==
autonumber
MM <--] : External Data
MM --> MM: Update pricing
MM -> Quay: HTTP POST: <url>/listings
note right #red
**ask**
end note
note left
Pricing JSON structure
end note
Trader -> Quay: HTTP GET: <url>/listings
autonumber stop

hnote over MM #lightBlue
some time later
end hnote
autonumber
MM <--] : External Data
MM --> MM: Update pricing
MM -> Quay: HTTP DELETE: <url>/listings/id
MM -> Quay: HTTP POST: <url>/listings
note left
Pricing JSON structure
end note
note right #red
**ask**
end note
Trader -> Quay: HTTP GET: <url>/listings
@enduml