@startuml

actor Trader
box Valorem #LightGreen
participant Quay
end box
actor "Market Maker" as MM
box Valorem #LightBlue
participant SettlementEngine as SE
end box

== Initialisation ==
MM --> Quay: Authenticate
MM --> Quay: gRPC RFQ Stream
Quay --> MM: gRPC RFQ Stream

== Case: Trader Lists, Market Maker Offer, Trader doesn't execute ==
autonumber
Trader --> SE: On-chain: write
Trader -> Quay: Create listing\nHTTP POST <url>/listings
note left #red
**ask**
end note
Trader -> Quay: gRPC: <server>/rfq
note right
ValoremQuoteRequest
end note
Quay -> MM: gRPC: RFQ Stream
note right
ValoremQuoteRequest
end note
MM -> Quay: Get listings\nHTTP GET <url>/listings/id
MM -> Quay: gRPC: RFQ Stream
note right
ValoremQuoteRequest: Some
end note
Quay -> Trader: gRPC: Offer
hnote over Trader #lightBlue
[Start of exercise window]
end hnote
hnote over Trader #lightBlue
[ End of exercise window ]
end hnote
Trader -[#red]-> Trader: Offer expiry
Trader --> SE: On-chain: redeem
@enduml